server:
  port: 8001
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/forum?serverTimezone=UTC&characterEncoding=utf-8
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    port: 6379
    host: localhost
    database: 3
  main:
    allow-bean-definition-overriding: true